
# SEO
title: Athena Jekyll Theme
description: A simple and elegant theme for Jekyll and GitHub Pages.

# social
social_link: twitter
social_username: broccolini
github_repo: athena # the GitHub repo name for your project
github_username: broccolini
theme_color: light

# Theme
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: '/mapping_latam'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


